// ---- Bookmark ---------------------------------------------------------------

export interface Bookmark {
  id: string; // namespaced: "${providerConfigId}:${rawId}"
  url: string;
  title: string;
  tag_names: string[];
  favicon_url?: string;
  // ISO timestamp of when the item was added/published, when the provider
  // knows it (linkding date_added, browser dateAdded, feed publish dates).
  // Basis for the per-folder "latest N" limit.
  date?: string;
  // ISO timestamp of linkding's date_modified. Only linkding populates this;
  // other providers leave it undefined. Basis for the "modified" sort mode
  // (falls back to `date` when absent).
  dateModified?: string;
}

export type BookmarkMap = Record<string, Bookmark>;

// ---- Folder rules -----------------------------------------------------------

export type ConditionType = "tag" | "url_contains" | "title_contains" | "provider";
export type MatchMode = "all" | "any" | "none";

export interface RuleCondition {
  type: ConditionType;
  value: string;
  // Only meaningful on a condition that is a direct child of an "any" (OR)
  // group; used by matchWeight() to bias folder display order. Unset/absent
  // conditions default to 0, so a folder with no weights configured never
  // has its order affected.
  weight?: number;
}

export interface RuleGroup {
  match: MatchMode;
  conditions: RuleNode[];
}

export type RuleNode = RuleCondition | RuleGroup;

/** Back-compat alias: a folder's rules are the root group. Old flat data is valid as-is. */
export type FolderRules = RuleGroup;

// Discriminator: groups have `conditions`; leaves have `type` + `value`.
export function isRuleGroup(node: RuleNode): node is RuleGroup {
  return "conditions" in node;
}

export interface Folder {
  id: string;
  name: string;
  rules: FolderRules;
  // Show only the newest N matches (by Bookmark.date, undated last). Absent = all.
  limit?: number;
  // Secondary display-order tiebreak, applied after matchWeight() scoring.
  // Absent = today's behavior (no explicit ordering beyond weight ties).
  sort?: "added" | "modified" | "alphabetical";
  bookmark_ids: string[]; // precomputed at sync time
}

// ---- Remote folder source -----------------------------------------------------

// Optional remote source of truth for the folder definitions: a JSON file (same
// format as the options page's folder export) fetched from a web server. While
// configured, every refresh REPLACES all folders and local folder editing is
// disabled in the options UI.
export interface FolderSourceConfig {
  url: string;
  // Refresh automatically every N minutes. Absent = manual refresh only
  // ("Sync folders now" buttons and after Save/URL changes).
  syncIntervalMinutes?: number;
}

// Bookkeeping for the folder source (storage key: folderSourceState).
export interface FolderSourceState {
  lastSyncAt: string; // ISO — last successful fetch ("" = never)
  lastAttemptAt: string; // ISO — last attempt incl. failures (due-check basis)
  fingerprint: string; // the source URL this state belongs to
  // HTTP validators from the last 200 response (conditional GET).
  etag?: string;
  lastModified?: string;
  // FNV-1a of the last successfully fetched body — detects an unchanged file
  // even when the server sends no usable validators, so folder ids (freshly
  // generated by parseFolders when the file carries none) don't churn.
  contentHash?: string;
}

// ---- Provider configs -------------------------------------------------------

export type ProviderType = "static" | "json" | "browser" | "linkding" | "feed" | "jsonfeed";

interface BaseProviderConfig {
  id: string;
  type: ProviderType;
  name: string;
}

export interface StaticProviderConfig extends BaseProviderConfig {
  type: "static";
}

export interface JsonProviderConfig extends BaseProviderConfig {
  type: "json";
  data: string;
}

export interface BrowserProviderConfig extends BaseProviderConfig {
  type: "browser";
  // Optional override of Settings.syncIntervalMinutes for this provider only.
  syncIntervalMinutes?: number;
}

export interface LinkdingProviderConfig extends BaseProviderConfig {
  type: "linkding";
  url: string;
  token: string;
  username?: string; // display label only; not sent to the linkding API (token auth)
  // Optional override of Settings.syncIntervalMinutes for this provider only.
  syncIntervalMinutes?: number;
  // How often (hours) an incremental-capable provider is forced through a FULL
  // sync — the only way to catch deletions/archiving, which modified_since
  // can't report. Absent = 24 (DEFAULT_FULL_SYNC_HOURS in shared/sync.ts).
  fullSyncIntervalHours?: number;
}

export interface FeedProviderConfig extends BaseProviderConfig {
  // Web feed: JSON Feed, RSS, or Atom — auto-detected at sync time.
  // "jsonfeed" is a legacy alias from before RSS/Atom support (never store-released,
  // but may exist in local storage); treated identically everywhere.
  type: "feed" | "jsonfeed";
  url: string;
  // Linkblog JSON Feeds (e.g. Daring Fireball) set external_url to the linked page
  // and url to their own commentary permalink; this picks which one to bookmark.
  // RSS/Atom have no such distinction — ignored there.
  preferExternalUrl: boolean;
  // Keep only the newest N feed items at sync time (some feeds ship 150+).
  // Absent = keep all.
  maxItems?: number;
  // Optional override of Settings.syncIntervalMinutes for this provider only.
  syncIntervalMinutes?: number;
  // How often (hours) to skip the conditional GET and force an unconditional
  // full fetch. Absent = 24 (DEFAULT_FULL_SYNC_HOURS in shared/sync.ts).
  fullSyncIntervalHours?: number;
}

export type ProviderConfig =
  | StaticProviderConfig
  | JsonProviderConfig
  | BrowserProviderConfig
  | LinkdingProviderConfig
  | FeedProviderConfig;

// ---- Provider interface -----------------------------------------------------

// What the background loop knows from the provider's previous successful sync;
// lets a provider fetch only what changed instead of the full corpus.
export interface SyncContext {
  // True when the loop requires a full sync (first sync, config changed, or the
  // periodic deletion-reconciliation full sync is due) — ignore the fields below.
  full: boolean;
  // linkding: highest date_modified seen so far (server-side clock, so client
  // clock skew can't lose updates) — becomes the modified_since query.
  since?: string;
  // Feeds: HTTP validators from the last 200 response, sent as
  // If-None-Match / If-Modified-Since for a conditional GET.
  etag?: string;
  lastModified?: string;
}

export interface SyncResult {
  // full: `bookmarks` is the provider's complete current corpus (replaces the
  //   provider's slice of the stored map).
  // incremental: `bookmarks` holds only new/changed items (upserted into the
  //   slice) — deletions are invisible until the next full sync.
  // unchanged: source not modified (feed 304); `bookmarks` is empty, keep slice.
  kind: "full" | "incremental" | "unchanged";
  bookmarks: Bookmark[];
  // Fresh HTTP validators (feeds, from a 200 response) for the next sync.
  etag?: string;
  lastModified?: string;
}

export interface BookmarkProvider {
  sync(ctx?: SyncContext): Promise<SyncResult>;
}

// ---- Per-provider sync state (storage key: providerSyncState) ---------------

export interface ProviderSyncState {
  lastSyncAt: string; // ISO — last successful sync of any kind ("" = never)
  lastAttemptAt: string; // ISO — last attempt incl. failures (due-check basis)
  lastFullSyncAt: string; // ISO — last successful FULL sync ("" = never)
  // providerFingerprint() of the config that produced this state; a mismatch
  // (URL/token/… changed) forces the next sync to be full.
  fingerprint: string;
  // linkding: highest date_modified seen (ISO; lexicographically comparable).
  cursor?: string;
  // Feeds: validators from the last 200 response.
  etag?: string;
  lastModified?: string;
}

export type ProviderSyncStateMap = Record<string, ProviderSyncState>;

// ---- Storage schema ---------------------------------------------------------

export interface StorageSchema {
  bookmarks: BookmarkMap;
  folders: Folder[];
  lastSync: string | null;
  settings: Settings;
  syncStatus: SyncStatus;
  providerSyncState: ProviderSyncStateMap;
  folderSourceState: FolderSourceState | null;
}

// ---- Sync status ------------------------------------------------------------

export interface SyncError {
  name: string; // provider name that failed
  message: string; // human-readable reason
  // Provider config id — since per-provider scheduling, a sync round only
  // touches the providers that were due, so statuses are merged by this key
  // (an error sticks until its provider is attempted again or removed).
  providerId?: string;
}

export interface SyncStatus {
  at: string; // ISO timestamp of the sync that produced this status
  errors: SyncError[];
}

// ---- Settings ---------------------------------------------------------------

export type Theme = "system" | "light" | "dark";

export interface Settings {
  syncIntervalMinutes: number;
  providers: ProviderConfig[];
  theme: Theme;
  // New-tab launcher only: close the New Tab page after "Open all in
  // background tabs" on a folder. Default is to keep it open (consistent with
  // the per-bookmark background button, which never closes the current view).
  newTabCloseOnOpenAll: boolean;
  // Remote source of truth for folder definitions. Absent = folders are edited
  // locally in the options page (the default).
  folderSource?: FolderSourceConfig;
}

export const DEFAULT_SETTINGS: Settings = {
  syncIntervalMinutes: 15,
  providers: [
    { id: "static-default", type: "static", name: "Static" },
  ],
  theme: "system",
  newTabCloseOnOpenAll: false,
};

// ---- Messages ---------------------------------------------------------------

export type MessageType = "sync_requested" | "sync_provider";

export interface Message {
  type: MessageType;
  // sync_provider only: the single provider to force-sync now.
  providerId?: string;
  // sync_provider only: force a FULL sync — bypass the incremental cursor so
  // deletions/archiving are picked up immediately ("Full sync now" button).
  full?: boolean;
}

// ---- Linkding API response --------------------------------------------------

export interface LinkdingBookmark {
  id: number;
  url: string;
  title: string;
  description: string;
  notes: string;
  web_archive_snapshot_url: string;
  favicon_url: string;
  preview_image_url: string;
  is_archived: boolean;
  unread: boolean;
  shared: boolean;
  tag_names: string[];
  date_added: string;
  date_modified: string;
}

export interface LinkdingResponse {
  count: number;
  next: string | null;
  previous: string | null;
  results: LinkdingBookmark[];
}
